server:
  port: 8989
#jwt:
  #secret: secretkey123
spring:
  application:
    name: netflix-zuul-api-gateway-server
  datasource:
    url: jdbc:mysql://localhost:3306/multipletab
    username: newuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
zuul:
  routes:
    noteapp-service:
      path: /note-api/**
      url: http://localhost:8083
    taskapp-service:
      url: http://localhost:8082/updatetask
    userapp-service:
      path: /user-api/**
      url: http://localhost:8081
      
     
#multitenancy:
#  mtapp:
#    datasource:
#      url: jdbc:mysql://localhost:3306/master_db?useSSL=false
#      username: newuser
#      password: password
#      driverClassName: com.mysql.cj.jdbc.Driver
#      connectionTimeout: 20000
#      idleTimeout: 300000
#      minIdle: 5
#      poolName: masterdb-connection-pool
#      

      
      

