server:
  port: 8080
spring:
  application:
    name: MultiTenant-Schedular
  datasource:
    url: 'jdbc:postgresql://localhost:5432/ MultiTenant-Schedular'
    username: 'postgres'
    password: 'tiger'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  main:
    allow-circular-references: true